export const POST_FIRST="POST_FIRST"    
export const POST_SECOND="POST_SECOND"
export const POST_THIRD="POST_THIRD"
export const LOADING="LOADING"
export const ERROR="ERROR"


export const POST_DATA_FIRST="POST_DATA_FIRST"    
export const POST_DATA_SECOND="POST_DATA_SECOND"
export const POST_DATA_THIRD="POST_DATA_THIRD"


export const PATCH_DATA_FIRST="PATCH_DATA_FIRST"    
export const PATCH_DATA_SECOND="PATCH_DATA_SECOND"
export const PATCH_DATA_THIRD="PATCH_DATA_THIRD"


export const DELETE_DATA_FIRST="DELETE_DATA_FIRST"    
export const DELETE_DATA_SECOND="DELETE_DATA_SECOND"
export const DELETE_DATA_THIRD="DELETE_DATA_THIRD"